-- 003_lesson_descriptions.sql — nội dung diễn giải cho MỌI bài của giáo trình hiện có trong giao-trinh/csv/ (180 bài),
-- hiện ngay dưới tên bài ở màn "Bắt đầu" (child/lesson.js). Cần migration 020 (cột lessons.description).
-- Chạy TAY trong SQL Editor (Supabase), sau khi đã nhập đủ 5 file CSV giáo trình. Chạy lại nhiều lần không hại.
-- Chỉ BỔ SUNG: bài nào đã có description (sửa tay trong khu admin) thì GIỮ NGUYÊN, không bị ghi đè.
-- Khớp theo tên chủ đề + tên bài; bài không có trong CSDL (chưa nhập CSV) thì bỏ qua, không báo lỗi.

begin;

update public.lessons l set description = v.description
from (values

  -- ---- Cấp 2 · Từ vựng cơ bản (cap1-trung-tu-vung.csv) ----
  ('Chào hỏi và lễ phép', 'Chào hỏi', 'Bé học những câu chào hỏi đầu tiên: chào buổi sáng, tạm biệt, hẹn gặp lại, chúc ngủ ngon.'),
  ('Chào hỏi và lễ phép', 'Lễ phép', 'Bé học cách nói lễ phép: cảm ơn, xin lỗi, xin phép, dạ thưa.'),
  ('Gia đình', 'Người thân', 'Bé học tên gọi những người thân gần gũi nhất: bố, mẹ, ông, bà, anh, chị.'),
  ('Gia đình', 'Người trong nhà', 'Bé học thêm các từ về gia đình và những người sống chung trong nhà: em bé, cô, chú, bạn.'),
  ('Cơ thể', 'Khuôn mặt', 'Bé học tên các bộ phận trên khuôn mặt: mắt, mũi, miệng, tai.'),
  ('Cơ thể', 'Tay và chân', 'Bé học tên tay, chân và các bộ phận khác trên cơ thể.'),
  ('Con vật', 'Con vật quanh nhà', 'Bé học tên những con vật quen thuộc nuôi trong nhà: chó, mèo, gà, vịt, heo, bò, cá.'),
  ('Con vật', 'Con vật ở sở thú', 'Bé học tên những con vật lớn thường gặp ở sở thú: voi, hổ, khỉ, gấu, thỏ, hươu.'),
  ('Con vật', 'Con vật nhỏ', 'Bé học tên những con vật nhỏ bé quanh mình: bướm, ong, kiến, ếch, rùa, chim.'),
  ('Màu sắc', 'Các màu cơ bản', 'Bé học gọi tên 8 màu cơ bản: đỏ, xanh dương, xanh lá, vàng, cam, tím, đen, trắng.'),
  ('Màu sắc', 'Hình khối', 'Bé học tên các hình cơ bản: hình tròn, hình vuông, hình tam giác, hình thoi, trái tim.'),
  ('Số đếm', 'Một đến năm', 'Bé học đếm từ 0 đến 5.'),
  ('Số đếm', 'Sáu đến mười', 'Bé học đếm tiếp từ 6 đến 10, và làm quen với số 100.'),
  ('Ăn uống', 'Bữa cơm', 'Bé học tên những món ăn quen thuộc trong bữa cơm: cơm, phở, bánh mì, trứng, rau, canh.'),
  ('Ăn uống', 'Đồ uống và bánh kẹo', 'Bé học tên đồ uống và đồ ngọt yêu thích: sữa, nước, nước cam, kem, bánh, kẹo.'),
  ('Trái cây', 'Trái cây quen thuộc', 'Bé học tên những loại trái cây quen thuộc: chuối, táo, cam, nho, dưa hấu, xoài.'),
  ('Trái cây', 'Trái cây khác', 'Bé học thêm tên các loại trái cây khác: dâu tây, lê, dứa, đào, chanh, dừa.'),
  ('Đồ chơi và đồ dùng học tập', 'Đồ chơi', 'Bé học tên những món đồ chơi quen thuộc: bóng, gấu bông, diều, xếp hình, bóng bay, quà.'),
  ('Đồ chơi và đồ dùng học tập', 'Đồ dùng học tập', 'Bé học tên đồ dùng học tập: sách, bút, cặp, kéo, thước, bút màu.'),
  ('Ngôi nhà', 'Trong nhà', 'Bé học tên đồ vật trong nhà: giường, ghế, cửa, đèn, tivi, đồng hồ.'),
  ('Ngôi nhà', 'Nhà bếp và nhà tắm', 'Bé học tên đồ dùng trong bếp và nhà tắm: bát, thìa, đũa, cốc, chảo, xà phòng.'),
  ('Thiên nhiên và thời tiết', 'Thời tiết', 'Bé học từ chỉ thời tiết: nắng, mưa, mây, gió, tuyết, cầu vồng.'),
  ('Thiên nhiên và thời tiết', 'Trong thiên nhiên', 'Bé học tên các sự vật trong thiên nhiên: cây, hoa, lá, mặt trăng, ngôi sao, biển.'),
  ('Quần áo và xe cộ', 'Quần áo', 'Bé học tên các loại quần áo: áo, quần, váy, giày, mũ, tất.'),
  ('Quần áo và xe cộ', 'Xe cộ', 'Bé học tên các phương tiện đi lại: xe đạp, xe máy, ô tô, xe buýt, tàu hoả, máy bay.'),
  ('Việc hằng ngày và cảm xúc', 'Việc hằng ngày', 'Bé học từ chỉ hoạt động hằng ngày: ngủ, chạy, hát, vẽ, tắm, đi bộ.'),
  ('Việc hằng ngày và cảm xúc', 'Cảm xúc', 'Bé học gọi tên cảm xúc của mình: vui, buồn, giận, sợ, ngạc nhiên, buồn ngủ.'),
  ('Tết và Việt Nam', 'Ngày Tết', 'Bé học từ về ngày Tết cổ truyền: bánh chưng, lì xì, pháo hoa, đèn lồng, hoa đào.'),
  ('Tết và Việt Nam', 'Việt Nam', 'Bé học từ về những hình ảnh quen thuộc của Việt Nam: áo dài, nón lá, con trâu, cánh đồng lúa, cây tre.'),
  ('Giờ giấc', 'Buổi trong ngày', 'Bé học các buổi trong ngày: sáng, trưa, chiều, tối, đêm.'),
  ('Giờ giấc', 'Xem đồng hồ', 'Bé học các từ liên quan đến xem giờ: đồng hồ, giờ, phút, giây, rưỡi, kim đồng hồ.'),
  ('Thứ trong tuần', 'Bảy ngày trong tuần', 'Bé học tên bảy ngày trong tuần, từ thứ Hai đến Chủ Nhật.'),
  ('Thứ trong tuần', 'Hôm qua, hôm nay, ngày mai', 'Bé học các từ chỉ thời gian: hôm qua, hôm nay, ngày mai, tuần, tháng, năm.'),
  ('Vị trí', 'Trên dưới trong ngoài', 'Bé học các từ chỉ vị trí: trên, dưới, trong, ngoài, cạnh, giữa.'),

  -- ---- Cấp 3 · Câu ngắn (cap2-ga-con-cau-ngan.csv) ----
  ('Lễ phép với người thân', 'Chào và cảm ơn', 'Bé tập nói những câu chào hỏi và cảm ơn lễ phép với ông bà, bố mẹ, như “Con chào bà ạ.” và “Con cảm ơn mẹ ạ.”'),
  ('Gia đình của con', 'Nói về gia đình', 'Bé tập nói những câu đơn giản để giới thiệu về gia đình mình, như “Đây là bố.” và “Nhà con có bốn người.”'),
  ('Con cần gì', 'Nói điều con cần', 'Bé tập nói ra điều mình đang cần — đói, khát, buồn ngủ hay muốn đi vệ sinh — để người lớn hiểu và giúp đỡ.'),
  ('Bữa ăn', 'Ăn uống', 'Bé tập nói những câu quen thuộc trong bữa ăn, như “Con ăn cơm.” và “Cơm ngon quá!”'),
  ('Ở trường', 'Một ngày đi học', 'Bé tập nói những câu về một ngày ở trường: đi học, vẽ tranh, đọc sách, chơi với bạn.'),
  ('Tiếng kêu và thời tiết', 'Con vật kêu', 'Bé tập nói câu về tiếng kêu của các con vật quen thuộc và về thời tiết, như “Con mèo kêu meo meo.” và “Trời mưa rồi.”'),
  ('Tết và lễ hội', 'Ngày Tết', 'Bé tập nói những câu về ngày Tết, như “Chúc mừng năm mới!” và “Ông bà lì xì cho con.”'),
  ('Cảm xúc và lễ phép', 'Con cảm thấy', 'Bé tập nói câu diễn tả cảm xúc của mình và những câu lễ phép, như “Con vui quá!” và “Con xin phép ạ.”'),
  ('Việc đã làm, đang làm, sẽ làm', 'Con đang làm gì', 'Bé tập nói câu với “đang” để kể việc mình hoặc người thân đang làm ngay lúc này, như “Con đang ăn cơm.”'),
  ('Việc đã làm, đang làm, sẽ làm', 'Con đã làm, con sẽ làm', 'Bé tập nói câu với “đã” (việc đã xong) và “sẽ” (việc sắp làm), như “Con đã ăn cơm rồi.” và “Con sẽ đi ngủ.”'),

  -- ---- Cấp 1 · Học vần (cap3-ga-choai-hoc-van.csv) ----
  ('Sáu thanh điệu', 'Tên sáu thanh', 'Bé làm quen với tên gọi và dấu của 6 thanh điệu tiếng Việt: ngang, sắc, huyền, hỏi, ngã, nặng.'),
  ('Sáu thanh điệu', 'Nghe sáu thanh: ma', 'Bé nghe và phân biệt 6 thanh điệu qua tiếng “ma”: ma, má, mà, mả, mã, mạ.'),
  ('Sáu thanh điệu', 'Nghe các thanh: la', 'Bé nghe và phân biệt các thanh điệu qua tiếng “la”: la, lá, là, lả, lạ.'),
  ('Sáu thanh điệu', 'Nghe các thanh: cú', 'Bé nghe và phân biệt các thanh điệu qua tiếng “cú”: cú, cù, củ, cũ, cụ.'),
  ('Sáu thanh điệu', 'Nghe sáu thanh: ta', 'Bé nghe và phân biệt 6 thanh điệu qua tiếng “ta”: ta, tá, tà, tả, tã, tạ.'),
  ('Sáu thanh điệu', 'Nghe các thanh: bao', 'Bé nghe và phân biệt các thanh điệu qua tiếng “bao”: bao, báo, bào, bảo, bão.'),
  ('Sáu thanh điệu', 'Nghe các thanh: ve', 'Bé nghe và phân biệt các thanh điệu qua tiếng “ve”: ve, vé, vè, vẻ, vẽ.'),
  ('Sáu thanh điệu', 'Nghe các thanh: mai', 'Bé nghe và phân biệt các thanh điệu qua tiếng “mai”: mai, mái, mài, mải, mãi.'),
  ('Chữ cái', 'Nhóm 1: a o ô ơ', 'Bé làm quen với 4 chữ cái: a, o, ô, ơ.'),
  ('Chữ cái', 'Nhóm 1: từ có a o ô ơ', 'Bé tập đọc những tiếng có chữ a, o, ô, ơ: bà, cá, bò, cờ, bơ.'),
  ('Chữ cái', 'Nhóm 2: i e ê u ư', 'Bé làm quen với 5 chữ cái: i, e, ê, u, ư.'),
  ('Chữ cái', 'Nhóm 2: từ có i e ê u ư', 'Bé tập đọc những tiếng có chữ i, e, ê, u, ư: mì, khỉ, mẹ, lê, mũ.'),
  ('Chữ cái', 'Nhóm 3: b m n l', 'Bé làm quen với 4 chữ cái: b, m, n, l.'),
  ('Chữ cái', 'Nhóm 3: từ có b m n l', 'Bé tập đọc những tiếng có chữ b, m, n, l: bé, bó, mơ, nơ, lê.'),
  ('Chữ cái', 'Nhóm 4: t c k q d đ', 'Bé làm quen với 6 chữ cái: t, c, k, q, d, đ.'),
  ('Chữ cái', 'Nhóm 4: từ có t c k q d đ', 'Bé tập đọc những tiếng có chữ t, c, k, q, d, đ: tôm, cam, kéo, quà, dừa, đàn.'),
  ('Chữ cái', 'Nhóm 5: h g r s v x', 'Bé làm quen với 6 chữ cái: h, g, r, s, v, x.'),
  ('Chữ cái', 'Nhóm 5: từ có h g r s v x', 'Bé tập đọc những tiếng có chữ h, g, r, s, v, x: hổ, gạo, rau, sữa, vở, xôi.'),
  ('Chữ cái', 'Nhóm 6: ă â y p', 'Bé làm quen với 4 chữ cái: ă, â, y, p.'),
  ('Chữ cái', 'Nhóm 6: từ có ă â y', 'Bé tập đọc những tiếng có chữ ă, â, y: mắt, răng, cân, cây, mây, tay.'),
  ('Chữ hoa', 'Chữ hoa nhóm 1: A O Ô Ơ', 'Bé làm quen với chữ hoa A, O, Ô, Ơ và cách viết hoa tương ứng với chữ thường.'),
  ('Chữ hoa', 'Chữ hoa nhóm 2: I E Ê U Ư', 'Bé làm quen với chữ hoa I, E, Ê, U, Ư và cách viết hoa tương ứng với chữ thường.'),
  ('Chữ hoa', 'Chữ hoa nhóm 3: B M N L', 'Bé làm quen với chữ hoa B, M, N, L và cách viết hoa tương ứng với chữ thường.'),
  ('Chữ hoa', 'Chữ hoa nhóm 4: T C K Q D Đ', 'Bé làm quen với chữ hoa T, C, K, Q, D, Đ và cách viết hoa tương ứng với chữ thường.'),
  ('Chữ hoa', 'Chữ hoa nhóm 5: H G R S V X', 'Bé làm quen với chữ hoa H, G, R, S, V, X và cách viết hoa tương ứng với chữ thường.'),
  ('Chữ hoa', 'Chữ hoa nhóm 6: Ă Â Y P', 'Bé làm quen với chữ hoa Ă, Â, Y, P và cách viết hoa tương ứng với chữ thường.'),
  ('Chữ hoa', 'Chữ hoa ghép 1: Ch Gh Gi Kh Ng Ngh', 'Bé làm quen với các chữ ghép viết hoa: Ch, Gh, Gi, Kh, Ng, Ngh.'),
  ('Chữ hoa', 'Chữ hoa ghép 2: Nh Ph Qu Th Tr', 'Bé làm quen với các chữ ghép viết hoa: Nh, Ph, Qu, Th, Tr.'),
  ('Chữ hoa', 'Tên riêng viết hoa', 'Bé tập nhận biết và đọc câu có tên riêng cần viết hoa, như “An và Mai đi học.”'),
  ('Ghép âm với nguyên âm', 'Vần a', 'Bé tập ghép phụ âm với vần a để đọc các tiếng: ba, bà, cá, gà, lá, nhà.'),
  ('Ghép âm với nguyên âm', 'Vần e, ê', 'Bé tập ghép phụ âm với vần e, ê để đọc các tiếng: xe, bé, mẹ, chè, dê, hè.'),
  ('Ghép âm với nguyên âm', 'Vần i', 'Bé tập ghép phụ âm với vần i để đọc các tiếng: bi, bí, mì, khỉ, chị, đi.'),
  ('Ghép âm với nguyên âm', 'Vần o, ô, ơ', 'Bé tập ghép phụ âm với vần o, ô, ơ để đọc các tiếng: bò, cô, cờ, bơ, hồ, nơ.'),
  ('Ghép âm với nguyên âm', 'Vần u, ư', 'Bé tập ghép phụ âm với vần u, ư để đọc các tiếng: mũ, thú, củ, chữ, thư, tủ.'),
  ('Vần có âm cuối', 'Vần an, ăn, ân', 'Bé tập đọc các tiếng có vần an, ăn, ân: đàn, bạn, ăn, cân, chân.'),
  ('Vần có âm cuối', 'Vần am, ăm, âm', 'Bé tập đọc các tiếng có vần am, ăm, âm: cam, tắm, ấm, nấm, mâm.'),
  ('Vần có âm cuối', 'Vần at, ăt, ât', 'Bé tập đọc các tiếng có vần at, ăt, ât: hát, cát, bát, mắt, tất, mật.'),
  ('Vần có âm cuối', 'Vần ang, anh', 'Bé tập đọc các tiếng có vần ang, anh: vàng, tháng, sáng, chanh, xanh.'),
  ('Vần có âm cuối', 'Vần ac, ach, uc, ưc', 'Bé tập đọc các tiếng có vần ac, ach, uc, ưc: sách, lạc, nhạc, thác, gạch, cúc.'),
  ('Vần có âm cuối', 'Vần en, ên, in, it', 'Bé tập đọc các tiếng có vần en, ên, in, it: đèn, nến, nhện, vịt, thịt, chín.'),
  ('Vần có âm cuối', 'Vần on, ôm, ơm, ôp, ơp', 'Bé tập đọc các tiếng có vần on, ôm, ơm, ôp, ơp: nón, tròn, thơm, tôm, cơm.'),
  ('Vần có âm cuối', 'Vần ai, ay, ây', 'Bé tập đọc các tiếng có vần ai, ay, ây: hai, tay, cây, bay, chai, mây.'),
  ('Vần có âm cuối', 'Vần oi, ôi, ơi, ui', 'Bé tập đọc các tiếng có vần oi, ôi, ơi, ui: voi, tôi, xôi, núi, túi, bơi.'),
  ('Vần có âm cuối', 'Vần ao, eo', 'Bé tập đọc các tiếng có vần ao, eo: sao, cao, gạo, cáo, mèo, heo.'),
  ('Vần có âm cuối', 'Vần au, âu, êu', 'Bé tập đọc các tiếng có vần au, âu, êu: rau, màu, trâu, cầu, lều.'),
  ('Nguyên âm đôi', 'Vần ia, ua, ưa', 'Bé tập đọc các tiếng có nguyên âm đôi ia, ua, ưa: thìa, đĩa, cua, rùa, mưa, dừa.'),
  ('Nguyên âm đôi', 'Vần iê (yê)', 'Bé tập đọc các tiếng có nguyên âm đôi iê, yê: biển, tiền, kiến, miệng, điện.'),
  ('Nguyên âm đôi', 'Vần uô', 'Bé tập đọc các tiếng có nguyên âm đôi uô: chuối, muối, chuông, thuốc, buồm.'),
  ('Nguyên âm đôi', 'Vần ươ', 'Bé tập đọc các tiếng có nguyên âm đôi ươ: vườn, bướm, trường, đường, ngựa.'),
  ('Phụ âm ghép và chính tả', 'Âm ch và tr', 'Bé tập đọc và phân biệt các tiếng bắt đầu bằng ch và tr: chó, chim, trứng, trăng, trống.'),
  ('Phụ âm ghép và chính tả', 'Âm kh, gh và ngh', 'Bé tập đọc và phân biệt các tiếng bắt đầu bằng kh, gh, ngh: khỉ, khóa, ghế, nghé, nghĩ.'),
  ('Phụ âm ghép và chính tả', 'Âm gi, ng và nh', 'Bé tập đọc và phân biệt các tiếng bắt đầu bằng gi, ng, nh: giày, giường, ngô, ngủ, nhẫn.'),
  ('Phụ âm ghép và chính tả', 'Âm ph, qu và th', 'Bé tập đọc và phân biệt các tiếng bắt đầu bằng ph, qu, th: phở, quà, quả, thỏ, thuyền.'),
  ('Phụ âm ghép và chính tả', 'Luật chính tả: c/k/q, g/gh, ng/ngh', 'Bé học luật chính tả: khi nào viết c, k hay q, khi nào viết g hay gh, ng hay ngh.'),
  ('Đọc từ và câu ngắn', 'Đọc từ: con vật quanh nhà', 'Bé ôn lại và tập đọc trơn các từ chỉ con vật quen thuộc: chó, mèo, gà, vịt, heo, bò, cá.'),
  ('Đọc từ và câu ngắn', 'Đọc từ: người thân', 'Bé ôn lại và tập đọc trơn các từ chỉ người thân: bố, mẹ, ông, bà, anh, chị.'),
  ('Đọc từ và câu ngắn', 'Đọc từ: bữa cơm', 'Bé ôn lại và tập đọc trơn các từ về bữa cơm: cơm, phở, bánh mì, trứng, rau, canh.'),
  ('Đọc từ và câu ngắn', 'Đọc từ: trong nhà', 'Bé ôn lại và tập đọc trơn các từ về đồ vật trong nhà: giường, ghế, cửa, đèn, tivi, đồng hồ.'),
  ('Đọc từ và câu ngắn', 'Đọc câu: chào và cảm ơn', 'Bé tập đọc trơn những câu chào hỏi, cảm ơn lễ phép, như “Con chào bà ạ.”'),
  ('Đọc từ và câu ngắn', 'Đọc câu: nói về gia đình', 'Bé tập đọc trơn những câu giới thiệu về gia đình, như “Đây là bố.” và “Nhà con có bốn người.”'),
  ('Đọc từ và câu ngắn', 'Đọc câu: ăn uống', 'Bé tập đọc trơn những câu về bữa ăn, như “Con ăn cơm.” và “Cơm ngon quá!”'),
  ('Đọc từ và câu ngắn', 'Đọc câu: con vật kêu', 'Bé tập đọc trơn những câu về tiếng kêu con vật và thời tiết, như “Con mèo kêu meo meo.”'),

  -- ---- Cấp 4 · Đọc hiểu (cap4-ga-trong-doc-hieu.csv) ----
  ('Đọc đoạn văn ngắn', 'Gia đình của Nam', 'Bé đọc đoạn văn kể về gia đình bạn Nam — bố là bác sĩ, mẹ là cô giáo, có một em gái tên Mai — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Đọc đoạn văn ngắn', 'Buổi sáng của em', 'Bé đọc đoạn văn kể về một buổi sáng đi học: dậy sớm, đánh răng, ăn sáng, gặp bạn trên đường — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Đọc đoạn văn ngắn', 'Tết ở nhà bà', 'Bé đọc đoạn văn kể về ngày Tết ở nhà bà: gói bánh chưng, được lì xì, xem pháo hoa — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Đọc đoạn văn ngắn', 'Ngày mưa', 'Bé đọc đoạn văn tả một ngày trời mưa, tiếng ếch kêu và cầu vồng hiện ra sau mưa — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Đọc đoạn văn ngắn', 'Chú mèo của em', 'Bé đọc đoạn văn kể về chú mèo tên Mun lông đen, thích ngủ cạnh chủ — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Đọc đoạn văn ngắn', 'Ở trường', 'Bé đọc đoạn văn kể về một ngày ở trường: sân trường nhiều cây xanh, giờ ra chơi nhảy dây, học hát — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Truyện cổ tích và truyền thuyết', 'Sự tích bánh chưng bánh giầy (1)', 'Bé đọc phần đầu truyện Sự tích bánh chưng bánh giầy: vua Hùng muốn chọn người nối ngôi, các hoàng tử đi tìm của ngon vật lạ, riêng Lang Liêu nghèo được thần báo mộng — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Truyện cổ tích và truyền thuyết', 'Sự tích bánh chưng bánh giầy (2)', 'Bé đọc tiếp phần sau truyện: Lang Liêu làm bánh chưng vuông tượng trưng cho đất, bánh giầy tròn tượng trưng cho trời, và được vua chọn nối ngôi — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Truyện cổ tích và truyền thuyết', 'Thánh Gióng (1)', 'Bé đọc phần đầu truyện Thánh Gióng: cậu bé ba tuổi chưa biết nói bỗng cất tiếng xin vua rèn ngựa sắt, roi sắt để đánh giặc — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Truyện cổ tích và truyền thuyết', 'Thánh Gióng (2)', 'Bé đọc tiếp phần sau truyện: Gióng vươn vai thành tráng sĩ, đánh tan giặc rồi cưỡi ngựa sắt bay về trời — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Truyện cổ tích và truyền thuyết', 'Sự tích Hồ Gươm', 'Bé đọc truyện Sự tích Hồ Gươm: Lê Lợi được Long Quân cho mượn gươm thần đánh giặc, sau đó trả gươm cho Rùa Vàng — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Truyện cổ tích và truyền thuyết', 'Con Rồng cháu Tiên', 'Bé đọc truyện Con Rồng cháu Tiên: Lạc Long Quân và Âu Cơ sinh ra bọc trăm trứng, các con chia nhau lên núi xuống biển — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Truyện cổ tích và truyền thuyết', 'Tấm Cám (1)', 'Bé đọc phần đầu truyện Tấm Cám: cô Tấm mồ côi sống khổ cực với dì ghẻ, được Bụt hiện lên giúp đỡ mỗi khi khóc — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Truyện cổ tích và truyền thuyết', 'Tấm Cám (2)', 'Bé đọc tiếp phần sau truyện: Tấm đánh rơi chiếc giày, nhà vua tìm được chủ nhân và cưới Tấm làm hoàng hậu — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Truyện cổ tích và truyền thuyết', 'Sơn Tinh và Thủy Tinh', 'Bé đọc truyện Sơn Tinh Thủy Tinh: hai vị thần cùng đến cầu hôn công chúa Mị Nương, Sơn Tinh thắng cuộc khiến Thủy Tinh dâng nước trả thù — rồi trả lời câu hỏi để kiểm tra hiểu bài.'),
  ('Ca dao, tục ngữ và đồng dao', 'Tục ngữ: biết ơn và gia đình', 'Bé đọc và tìm hiểu ý nghĩa những câu tục ngữ về lòng biết ơn và tình cảm gia đình, như “Uống nước nhớ nguồn.” và “Anh em như thể tay chân.”'),
  ('Ca dao, tục ngữ và đồng dao', 'Tục ngữ: học tập và đoàn kết', 'Bé đọc và tìm hiểu ý nghĩa những câu tục ngữ về học tập chăm chỉ và đoàn kết, như “Có công mài sắt, có ngày nên kim.”'),
  ('Ca dao, tục ngữ và đồng dao', 'Ca dao và đồng dao', 'Bé đọc những câu ca dao, đồng dao quen thuộc của tuổi thơ Việt Nam, như “Con cò bé bé” và “Dung dăng dung dẻ.”'),
  ('Viết đúng chính tả', 'Viết hoa đầu câu và tên riêng', 'Bé học quy tắc viết hoa chữ cái đầu câu và tên riêng người, địa danh, qua các câu như “Hà Nội là thủ đô của Việt Nam.”'),
  ('Viết đúng chính tả', 'Dấu câu: chấm, chấm hỏi, chấm than', 'Bé học cách dùng dấu chấm, dấu chấm hỏi và dấu chấm than đúng chỗ trong câu.'),
  ('Viết đúng chính tả', 'Chính tả: c, k, q, g, gh, ng, ngh', 'Bé luyện viết đúng chính tả các âm dễ nhầm: c/k/q, g/gh, ng/ngh.'),
  ('Viết đúng chính tả', 'Chính tả: ch, tr, s, x, d, gi, r', 'Bé luyện viết đúng chính tả các âm dễ nhầm: ch/tr, s/x, d/gi/r.'),
  ('Từ chỉ hoạt động và đặc điểm', 'Từ chỉ hoạt động', 'Bé học các từ chỉ hoạt động: nhảy, bơi, viết, đọc, hát, múa, cười, khóc.'),
  ('Từ chỉ hoạt động và đặc điểm', 'Từ chỉ đặc điểm', 'Bé học các từ chỉ đặc điểm, tính chất: to, nhỏ, cao, nhanh, chậm, nóng, lạnh.'),
  ('Từ chỉ hoạt động và đặc điểm', 'Đặt câu với từ chỉ đặc điểm', 'Bé tập đặt câu có dùng từ chỉ đặc điểm, như “Con báo chạy rất nhanh.” và “Con voi rất to.”'),
  ('Kể chuyện theo tranh', 'Em trồng cây', 'Bé đọc và sắp xếp các câu kể lại quá trình trồng cây: gieo hạt, tưới nước, hạt nảy mầm, cây nở hoa.'),
  ('Kể chuyện theo tranh', 'Đi chợ cùng mẹ', 'Bé đọc và sắp xếp các câu kể lại một buổi đi chợ cùng mẹ vào sáng chủ nhật.'),
  ('Kể chuyện theo tranh', 'Cơn mưa và cầu vồng', 'Bé đọc và sắp xếp các câu kể lại một cơn mưa bất chợt và cầu vồng hiện ra sau đó.'),
  ('Kể chuyện theo tranh', 'Sinh nhật của Lan', 'Bé đọc và sắp xếp các câu kể lại buổi sinh nhật sáu tuổi của bạn Lan.'),

  -- ---- Chủ đề hội thoại (hoi-thoai-giao-tiep.csv, 4 cấp) ----
  ('Chủ đề hội thoại cấp 3', 'Làm quen', 'Bé nghe và tập nói theo tình huống làm quen: chào hỏi, hỏi tên, hỏi tuổi, và tạm biệt.'),
  ('Chủ đề hội thoại cấp 3', 'Lễ phép', 'Bé nghe và tập nói theo tình huống lễ phép hằng ngày: cảm ơn, xin lỗi, xin phép, chúc ngủ ngon.'),
  ('Chủ đề hội thoại cấp 3', 'Gia đình của con', 'Bé nghe và tập nói giới thiệu về gia đình mình: có những ai, nghề nghiệp bố mẹ.'),
  ('Chủ đề hội thoại cấp 3', 'Con cần gì', 'Bé nghe và tập nói khi cần điều gì đó: đồ ăn, nước uống, sự giúp đỡ.'),
  ('Chủ đề hội thoại cấp 3', 'Bữa ăn', 'Bé nghe và tập nói những câu lễ phép trong bữa ăn: mời cơm, xin thêm, báo đã ăn xong.'),
  ('Chủ đề hội thoại cấp 3', 'Ở trường', 'Bé nghe và tập nói về một ngày đi học: học gì, chơi với ai, giờ ra chơi.'),
  ('Chủ đề hội thoại cấp 3', 'Tiếng kêu và thời tiết', 'Bé nghe và tập nói về tiếng kêu con vật và cách ứng phó với thời tiết.'),
  ('Chủ đề hội thoại cấp 3', 'Tết và lễ hội', 'Bé nghe và tập nói về không khí ngày Tết: lì xì, bánh chưng, chúc Tết ông bà.'),
  ('Chủ đề hội thoại cấp 3', 'Cảm xúc và lễ phép', 'Bé nghe và tập nói để diễn tả cảm xúc: vui, buồn, sợ, tức giận.'),
  ('Chủ đề hội thoại cấp 3', 'Việc đã làm, đang làm, sẽ làm', 'Bé nghe và tập nói theo ba thì: việc đã làm, đang làm và sẽ làm.'),
  ('Chủ đề hội thoại cấp 1', 'Con vật quanh nhà', 'Bé nghe và tập nói về những con vật quen thuộc nuôi trong nhà: gọi tên và bắt chước tiếng kêu.'),
  ('Chủ đề hội thoại cấp 1', 'Người thân', 'Bé nghe và tập nói về những người thân trong nhà: ông bà, bố mẹ.'),
  ('Chủ đề hội thoại cấp 1', 'Bữa cơm', 'Bé nghe và tập nói những câu đơn giản trong bữa cơm: đã ăn chưa, thích ăn gì.'),
  ('Chủ đề hội thoại cấp 1', 'Trong nhà', 'Bé nghe và tập nói về vị trí đồ vật quen thuộc trong nhà.'),
  ('Chủ đề hội thoại cấp 1', 'Chào và cảm ơn', 'Bé nghe và tập nói những câu chào hỏi và cảm ơn đơn giản đầu tiên.'),
  ('Chủ đề hội thoại cấp 1', 'Gia đình', 'Bé nghe và tập nói về số người trong nhà và ai nấu cơm.'),
  ('Chủ đề hội thoại cấp 1', 'Ăn uống', 'Bé nghe và tập nói những câu đơn giản khi ăn uống: muốn uống gì, có đói không.'),
  ('Chủ đề hội thoại cấp 1', 'Con vật kêu', 'Bé nghe và tập nói tiếng kêu của những con vật quen thuộc.'),
  ('Chủ đề hội thoại cấp 2', 'Lời chào trong ngày', 'Bé nghe và tập nói lời chào phù hợp với từng thời điểm và người trong ngày.'),
  ('Chủ đề hội thoại cấp 2', 'Gia đình', 'Bé nghe và tập nói về các thành viên trong gia đình và thứ tự con trong nhà.'),
  ('Chủ đề hội thoại cấp 2', 'Cơ thể', 'Bé nghe và tập nói về công dụng của mắt, tai, chân trên cơ thể.'),
  ('Chủ đề hội thoại cấp 2', 'Con vật', 'Bé nghe và tập nói về con vật yêu thích, tiếng kêu và khả năng của từng con vật.'),
  ('Chủ đề hội thoại cấp 2', 'Màu sắc', 'Bé nghe và tập nói tên màu sắc của bầu trời, quả chuối và màu mình thích.'),
  ('Chủ đề hội thoại cấp 2', 'Số đếm', 'Bé nghe và tập nói khi đếm số và làm phép cộng đơn giản.'),
  ('Chủ đề hội thoại cấp 2', 'Ăn uống', 'Bé nghe và tập nói khi được hỏi muốn ăn gì, uống gì.'),
  ('Chủ đề hội thoại cấp 2', 'Trái cây', 'Bé nghe và tập nói về loại quả yêu thích và vị của trái cây.'),
  ('Chủ đề hội thoại cấp 2', 'Đồ chơi và đồ dùng học tập', 'Bé nghe và tập nói về đồ chơi đang chơi và đồ dùng học tập cần dùng.'),
  ('Chủ đề hội thoại cấp 2', 'Ngôi nhà', 'Bé nghe và tập nói về các phòng trong nhà và việc làm ở từng phòng.'),
  ('Chủ đề hội thoại cấp 2', 'Thiên nhiên và thời tiết', 'Bé nghe và tập nói về thời tiết trong ngày và cần chuẩn bị gì.'),
  ('Chủ đề hội thoại cấp 2', 'Quần áo và xe cộ', 'Bé nghe và tập nói về quần áo đang mặc và phương tiện đi học.'),
  ('Chủ đề hội thoại cấp 2', 'Việc hằng ngày và cảm xúc', 'Bé nghe và tập nói về việc làm buổi sáng và cảm xúc trong ngày.'),
  ('Chủ đề hội thoại cấp 2', 'Tết và Việt Nam', 'Bé nghe và tập nói về những điều thích nhất ngày Tết và quê hương Việt Nam.'),
  ('Chủ đề hội thoại cấp 2', 'Giờ giấc', 'Bé nghe và tập nói về giờ giấc sinh hoạt trong ngày.'),
  ('Chủ đề hội thoại cấp 2', 'Thứ trong tuần', 'Bé nghe và tập nói về thứ trong tuần, hôm nay và ngày mai.'),
  ('Chủ đề hội thoại cấp 2', 'Vị trí', 'Bé nghe và tập nói về vị trí của đồ vật và bản thân.'),
  ('Chủ đề hội thoại cấp 4', 'Gia đình của Nam', 'Bé nghe và tập nói khi kể lại về gia đình bạn Nam trong bài đọc.'),
  ('Chủ đề hội thoại cấp 4', 'Buổi sáng của em', 'Bé nghe và tập nói khi kể lại buổi sáng thường ngày của mình.'),
  ('Chủ đề hội thoại cấp 4', 'Tết ở nhà bà', 'Bé nghe và tập nói khi kể lại một cái Tết ở nhà bà.'),
  ('Chủ đề hội thoại cấp 4', 'Ngày mưa', 'Bé nghe và tập nói khi kể lại một ngày mưa ở trong nhà.'),
  ('Chủ đề hội thoại cấp 4', 'Chú mèo của em', 'Bé nghe và tập nói khi kể về chú mèo nuôi trong nhà.'),
  ('Chủ đề hội thoại cấp 4', 'Ở trường', 'Bé nghe và tập nói khi kể về môn học, cô giáo và bạn bè ở trường.'),
  ('Chủ đề hội thoại cấp 4', 'Em trồng cây', 'Bé nghe và tập nói khi kể lại quá trình trồng và chăm sóc một cây non.'),
  ('Chủ đề hội thoại cấp 4', 'Đi chợ cùng mẹ', 'Bé nghe và tập nói khi kể lại một buổi đi chợ cùng mẹ.'),
  ('Chủ đề hội thoại cấp 4', 'Cơn mưa và cầu vồng', 'Bé nghe và tập nói khi kể lại một cơn mưa và cầu vồng xuất hiện sau đó.'),
  ('Chủ đề hội thoại cấp 4', 'Sinh nhật của Lan', 'Bé nghe và tập nói khi kể lại buổi sinh nhật của bạn Lan.')

) as v(unit_title, title_vi, description)
join public.units un on un.title_vi = v.unit_title
where l.unit_id = un.id and l.title_vi = v.title_vi and l.description is null;

commit;
