-- 022_bai_ban.sql — Giai đoạn 1 (nền dữ liệu) của "Tiếng Việt Bài Bản": giáo trình có cấu trúc cho người lớn/người
-- nước ngoài học tiếng Việt. Đây là 1 GIAO DIỆN HỌC KHÁC trong CÙNG 1 app/tài khoản/dự án Supabase — KHÔNG phải
-- app/hệ thống riêng, KHÔNG có mô hình thu phí riêng (đã chốt — xem artifact "Tiếng Việt Bài Bản", mục 06–07).
-- Dùng lại is_admin()/has_access() và cơ chế duyệt/nháp sẵn có; KHÔNG đổi trigger child_slots/phí thêm con
-- (payments_before_update, migration 001) — người học bài bản vẫn tính vào child_slots như con bình thường.
--
-- Phân cấp: bb_levels (CEFR A1/A2/B1…) > bb_units (chủ đề) > bb_lessons (bài, có lesson_type) > bb_lesson_steps
-- (chặng tuần tự trong 1 bài: hội thoại · từ vựng · ngữ pháp · ngữ âm · mini-game · đọc hiểu · luyện viết) > bảng
-- nội dung riêng theo từng loại chặng (bb_dialogue_lines, bb_vocab, bb_grammar, bb_phonics_pairs,
-- bb_reading_passages/bb_reading_questions, bb_writing_tasks). Mini-game (chặng 'minigame') KHÔNG có bảng nội dung
-- riêng — chạy runtime từ chính bb_vocab/bb_phonics_pairs của bài (làm ở giai đoạn 4, xem kế hoạch mục 07).
--
-- Người học bài bản dùng LẠI nguyên bảng child_profiles (không tạo bảng hồ sơ riêng) — chỉ thêm cột profile_type để
-- phân biệt giao diện lúc vào app (decideScreen(), giai đoạn 2).
--
-- Đây là migration ĐẦU TIÊN sau 001_init.sql tạo bảng mới (mọi migration 002–021 chỉ ALTER bảng có sẵn), nên các
-- lệnh CREATE TABLE/POLICY dưới đây được viết an toàn để CHẠY LẠI NHIỀU LẦN KHÔNG HẠI (IF NOT EXISTS / DROP trước
-- khi CREATE), đúng quy ước của mọi migration từ 002 trở đi.
-- Chạy TAY trong SQL Editor (sau 001–021).

-- ---------- child_profiles: phân biệt hồ sơ "con" và hồ sơ "người học bài bản" -------------------------------------
alter table public.child_profiles add column if not exists profile_type text not null default 'child';
alter table public.child_profiles drop constraint if exists child_profiles_profile_type_check;
alter table public.child_profiles add constraint child_profiles_profile_type_check
  check (profile_type in ('child', 'learner'));

-- ---------- cấp độ (mã CEFR: A1, A2, B1, B2, C1, C2) ----------------------------------------------------------------
create table if not exists public.bb_levels (
  id bigint generated by default as identity primary key,
  code text not null unique check (code ~ '^[ABC][12]$'),
  name_vi text not null,
  can_do text,                                    -- "có thể làm được gì" (can-do statement kiểu CEFR), free text
  sort_order int not null default 0,
  status text not null default 'draft' check (status in ('draft', 'approved')),
  created_at timestamptz not null default now()
);

-- ---------- chủ đề lớn trong 1 cấp -------------------------------------------------------------------------------
create table if not exists public.bb_units (
  id bigint generated by default as identity primary key,
  level_id bigint not null references public.bb_levels (id) on delete cascade,
  title_vi text not null,
  emoji text,
  description text,
  sort_order int not null default 0,
  status text not null default 'draft' check (status in ('draft', 'approved')),
  created_at timestamptz not null default now()
);
create index if not exists bb_units_level_idx on public.bb_units (level_id);

-- ---------- bài trong 1 chủ đề ------------------------------------------------------------------------------------
create table if not exists public.bb_lessons (
  id bigint generated by default as identity primary key,
  unit_id bigint not null references public.bb_units (id) on delete cascade,
  title_vi text not null,
  title_tr jsonb not null default '{}'::jsonb,     -- {"de":"...", "en":"..."} theo LANGUAGES của bản triển khai
  lesson_type text not null default 'core' check (lesson_type in ('core', 'review', 'reading', 'writing')),
  description text,
  sort_order int not null default 0,
  status text not null default 'draft' check (status in ('draft', 'approved')),
  created_at timestamptz not null default now()
);
create index if not exists bb_lessons_unit_idx on public.bb_lessons (unit_id);

-- ---------- chặng trong 1 bài (thứ tự tuần tự = sort_order) --------------------------------------------------------
create table if not exists public.bb_lesson_steps (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.bb_lessons (id) on delete cascade,
  step_type text not null check (step_type in
    ('dialogue', 'vocab', 'grammar', 'phonics', 'minigame', 'reading', 'writing')),
  config jsonb not null default '{}'::jsonb,       -- vd mini-game: {"kind":"flashcard_srs"}
  sort_order int not null default 0,
  status text not null default 'draft' check (status in ('draft', 'approved')),
  created_at timestamptz not null default now()
);
create index if not exists bb_lesson_steps_lesson_idx on public.bb_lesson_steps (lesson_id);

-- ---------- nội dung chặng Hội thoại ------------------------------------------------------------------------------
create table if not exists public.bb_dialogue_lines (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.bb_lesson_steps (id) on delete cascade,
  speaker text not null default 'A',               -- vai trong hội thoại (vd 'A'/'B'), khác quy ước dialogue trẻ em
  line_vi text not null,
  line_tr jsonb not null default '{}'::jsonb,
  audio_path text,
  sort_order int not null default 0
);
create index if not exists bb_dialogue_lines_step_idx on public.bb_dialogue_lines (step_id);

-- ---------- nội dung chặng Từ vựng --------------------------------------------------------------------------------
create table if not exists public.bb_vocab (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.bb_lesson_steps (id) on delete cascade,
  word_vi text not null,
  pos text,                                        -- loại từ: n, v, adj, adv…
  meaning jsonb not null default '{}'::jsonb,       -- {"de":"...", "en":"..."}
  image_path text,
  audio_path text,
  sort_order int not null default 0
);
create index if not exists bb_vocab_step_idx on public.bb_vocab (step_id);

-- ---------- nội dung chặng Ngữ pháp -------------------------------------------------------------------------------
create table if not exists public.bb_grammar (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.bb_lesson_steps (id) on delete cascade,
  formula text not null,                           -- "công thức hình họa", vd "Chào + đại từ"
  formula_tr jsonb not null default '{}'::jsonb,
  examples jsonb not null default '[]'::jsonb,      -- [{"vi":"...", "tr":{"de":"..."}}]
  sort_order int not null default 0
);
create index if not exists bb_grammar_step_idx on public.bb_grammar (step_id);

-- ---------- nội dung chặng Ngữ âm ---------------------------------------------------------------------------------
create table if not exists public.bb_phonics_pairs (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.bb_lesson_steps (id) on delete cascade,
  sound_a text not null,
  sound_b text not null,
  examples jsonb not null default '[]'::jsonb,      -- vd cặp từ minh hoạ dễ nhầm
  audio_a_path text,
  audio_b_path text,
  sort_order int not null default 0
);
create index if not exists bb_phonics_pairs_step_idx on public.bb_phonics_pairs (step_id);

-- ---------- nội dung chặng Đọc hiểu -------------------------------------------------------------------------------
create table if not exists public.bb_reading_passages (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.bb_lesson_steps (id) on delete cascade,
  passage_vi text not null,
  passage_tr jsonb not null default '{}'::jsonb,
  audio_path text
);
create index if not exists bb_reading_passages_step_idx on public.bb_reading_passages (step_id);

create table if not exists public.bb_reading_questions (
  id bigint generated by default as identity primary key,
  passage_id bigint not null references public.bb_reading_passages (id) on delete cascade,
  question_vi text not null,
  choices jsonb not null default '[]'::jsonb,
  answer int not null check (answer >= 1),          -- đếm từ 1, cùng quy ước content_items.extra Cấp 4 (app trẻ em)
  sort_order int not null default 0
);
create index if not exists bb_reading_questions_passage_idx on public.bb_reading_questions (passage_id);

-- ---------- nội dung chặng Luyện viết -----------------------------------------------------------------------------
create table if not exists public.bb_writing_tasks (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.bb_lesson_steps (id) on delete cascade,
  task_type text not null check (task_type in ('fill', 'order', 'write')),
  prompt_vi text not null,
  prompt_tr jsonb not null default '{}'::jsonb,
  -- hình dạng tuỳ task_type: fill {"sentence":"...","answer":"..."} · order {"words":[...]} · write {"min_words":20,"sample":"..."}
  content jsonb not null default '{}'::jsonb,
  sort_order int not null default 0
);
create index if not exists bb_writing_tasks_step_idx on public.bb_writing_tasks (step_id);

-- ============================================================================
-- RLS — cùng luật với nội dung trẻ em: admin xem/sửa hết; người dùng chỉ đọc mục ĐÃ DUYỆT khi còn hạn (has_access()).
-- ============================================================================

-- Bảng có status riêng (bb_levels/bb_units/bb_lessons/bb_lesson_steps): duyệt/nháp giống units/lessons/content_items.
do $$
declare t text;
begin
  foreach t in array array['bb_levels', 'bb_units', 'bb_lessons', 'bb_lesson_steps'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_read', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (public.is_admin() or (status = ''approved'' and public.has_access()))',
      t || '_read', t);
    execute format('drop policy if exists %I on public.%I', t || '_admin_write', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      t || '_admin_write', t);
  end loop;
end $$;

-- Nội dung theo chặng (không có status riêng): đọc được khi chặng CHA đã duyệt + còn hạn; ghi chỉ admin.
do $$
declare t text;
begin
  foreach t in array array['bb_dialogue_lines', 'bb_vocab', 'bb_grammar', 'bb_phonics_pairs',
                            'bb_reading_passages', 'bb_writing_tasks'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_read', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (public.is_admin() or (public.has_access() and exists (select 1 from public.bb_lesson_steps s where s.id = step_id and s.status = ''approved'')))',
      t || '_read', t);
    execute format('drop policy if exists %I on public.%I', t || '_admin_write', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      t || '_admin_write', t);
  end loop;
end $$;

-- Câu hỏi đọc hiểu: đi qua bảng đoạn văn để tới chặng (không có step_id trực tiếp).
alter table public.bb_reading_questions enable row level security;
drop policy if exists bb_reading_questions_read on public.bb_reading_questions;
create policy bb_reading_questions_read on public.bb_reading_questions for select to authenticated
  using (public.is_admin() or (public.has_access() and exists (
    select 1 from public.bb_reading_passages p join public.bb_lesson_steps s on s.id = p.step_id
     where p.id = passage_id and s.status = 'approved')));
drop policy if exists bb_reading_questions_admin_write on public.bb_reading_questions;
create policy bb_reading_questions_admin_write on public.bb_reading_questions for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
