-- 023_bb_progress.sql — Giai đoạn 4 (Luyện tập/SRS) của "Tiếng Việt Bài Bản": nền cho tiến độ + ôn tập kiểu Leitner
-- (xem KE_HOACH_TIENG_VIET_BAI_BAN.md mục 7 GĐ 4). Chạy TAY trong SQL Editor (sau 001–022). Chạy lại nhiều lần không hại.
--
-- bb_progress: chặng nào (bb_lesson_steps) người học đã đi qua (runner.js đánh dấu khi 1 chặng xong, xem
-- bb/runner.js) — dùng để: (1) đánh dấu bài đã xong ở danh sách bài, (2) chỉ mục đã GẶP QUA mới vào diện ôn tập
-- (không bắt ôn từ chưa học tới).
--
-- bb_srs_state: 1 dòng/mục/loại chặng (vocab | grammar | phonics | dialogue) người học đã gặp — `box` (hộp Leitner
-- 1–5) CHỈ có ý nghĩa với 'vocab' (tự đánh giá "Nhớ"/"Quên" ở màn Luyện tập); 3 loại còn lại không chấm, chỉ dùng
-- `due_at` để biết "lâu chưa ôn" (xem bb/srs.js). `item_id` là id trong đúng bảng nội dung tương ứng
-- (bb_vocab/bb_grammar/bb_phonics_pairs/bb_dialogue_lines) — KHÔNG có khoá ngoại (item_type quyết định bảng nào,
-- Postgres không có FK "tuỳ loại"; toàn vẹn do code kiểm, giống cách `activity_log.lesson_id` bên khu trẻ em không
-- ràng buộc chặt với mọi loại `kind`).
create table if not exists public.bb_progress (
  id bigint generated by default as identity primary key,
  child_id uuid not null references public.child_profiles (id) on delete cascade,
  step_id bigint not null references public.bb_lesson_steps (id) on delete cascade,
  completed_at timestamptz not null default now(),
  unique (child_id, step_id)
);
create index if not exists bb_progress_child_idx on public.bb_progress (child_id);

create table if not exists public.bb_srs_state (
  id bigint generated by default as identity primary key,
  child_id uuid not null references public.child_profiles (id) on delete cascade,
  item_type text not null check (item_type in ('vocab', 'grammar', 'phonics', 'dialogue')),
  item_id bigint not null,
  box smallint not null default 1 check (box between 1 and 5),
  due_at timestamptz not null default now(),
  reviewed_count int not null default 0,
  correct_count int not null default 0,
  updated_at timestamptz not null default now(),
  unique (child_id, item_type, item_id)
);
create index if not exists bb_srs_state_child_idx on public.bb_srs_state (child_id, item_type, due_at);

-- RLS — CÙNG luật với dữ liệu của con bên khu trẻ em (child_progress/activity_log ở 001_init.sql): đọc luôn được
-- (xuất/xoá dữ liệu); GHI chỉ khi còn hạn (has_access()) và đúng con của mình (hoặc admin).
do $$
declare t text;
begin
  foreach t in array array['bb_progress', 'bb_srs_state'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_read', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (public.is_admin() or exists (select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid()))',
      t || '_read', t);
    execute format('drop policy if exists %I on public.%I', t || '_insert', t);
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (public.is_admin() or (public.has_access() and exists (select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid())))',
      t || '_insert', t);
    execute format('drop policy if exists %I on public.%I', t || '_update', t);
    execute format(
      'create policy %I on public.%I for update to authenticated using (public.is_admin() or (public.has_access() and exists (select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid()))) with check (public.is_admin() or (public.has_access() and exists (select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid())))',
      t || '_update', t);
    execute format('drop policy if exists %I on public.%I', t || '_delete', t);
    execute format(
      'create policy %I on public.%I for delete to authenticated using (public.is_admin() or exists (select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid()))',
      t || '_delete', t);
  end loop;
end $$;
