-- "Tiếng Việt Bài Bản": thêm chặng "Luyện nghe" (step_type 'listening') — xếp sau 'reading' trong luồng chọn loại
-- chặng. Bảng nội dung mirror ĐÚNG bb_reading_passages/bb_reading_questions (đoạn văn + câu hỏi trắc nghiệm), chỉ
-- khác cách CHƠI ở frontend: Luyện nghe KHÔNG hiện chữ (passage_vi chỉ để admin soạn/tra + sinh audio_path), chỉ
-- cho nghe "cả đoạn" (audio_path) hoặc từng câu tách từ passage_vi lúc chạy (không cần audio riêng từng câu — xem
-- bb/steps/listening.js).
alter table public.bb_lesson_steps drop constraint if exists bb_lesson_steps_step_type_check;
alter table public.bb_lesson_steps add constraint bb_lesson_steps_step_type_check check (step_type in
  ('dialogue', 'vocab', 'grammar', 'phonics', 'minigame', 'reading', 'listening', 'writing'));

create table if not exists public.bb_listening_passages (
  id bigint generated by default as identity primary key,
  step_id bigint not null references public.bb_lesson_steps (id) on delete cascade,
  passage_vi text not null,
  passage_tr jsonb not null default '{}'::jsonb,
  audio_path text
);
create index if not exists bb_listening_passages_step_idx on public.bb_listening_passages (step_id);

create table if not exists public.bb_listening_questions (
  id bigint generated by default as identity primary key,
  passage_id bigint not null references public.bb_listening_passages (id) on delete cascade,
  question_vi text not null,
  choices jsonb not null default '[]'::jsonb,
  answer int not null check (answer >= 1),
  sort_order int not null default 0
);
create index if not exists bb_listening_questions_passage_idx on public.bb_listening_questions (passage_id);

alter table public.bb_listening_passages enable row level security;
drop policy if exists bb_listening_passages_read on public.bb_listening_passages;
create policy bb_listening_passages_read on public.bb_listening_passages for select to authenticated
  using (public.is_admin() or (public.has_access() and exists (
    select 1 from public.bb_lesson_steps s where s.id = step_id and s.status = 'approved')));
drop policy if exists bb_listening_passages_admin_write on public.bb_listening_passages;
create policy bb_listening_passages_admin_write on public.bb_listening_passages for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

alter table public.bb_listening_questions enable row level security;
drop policy if exists bb_listening_questions_read on public.bb_listening_questions;
create policy bb_listening_questions_read on public.bb_listening_questions for select to authenticated
  using (public.is_admin() or (public.has_access() and exists (
    select 1 from public.bb_listening_passages p join public.bb_lesson_steps s on s.id = p.step_id
     where p.id = passage_id and s.status = 'approved')));
drop policy if exists bb_listening_questions_admin_write on public.bb_listening_questions;
create policy bb_listening_questions_admin_write on public.bb_listening_questions for all to authenticated
  using (public.is_admin()) with check (public.is_admin());
