-- "Tiếng Việt Bài Bản": nhật ký các PHIÊN Luyện tập kiểu trò chơi (khu Trẻ em có activity_log.skill/source, Bài Bản dùng bảng
-- riêng vì activity_log.lesson_id/child_progress khoá cứng vào bảng khu Trẻ em). 1 dòng = 1 phiên của 1 kỹ năng (cộng
-- thêm 1 dòng/trò nhỏ trong phiên) — dùng cho huy hiệu 🥉🥈🥇 theo kỹ năng (đếm phiên từ 85 điểm trở lên) giống khu Trẻ em.
create table if not exists public.bb_practice_log (
  id bigint generated by default as identity primary key,
  child_id uuid not null references public.child_profiles (id) on delete cascade,
  skill text not null,
  kind text not null,                          -- tên trò (vd 'meaning_pick') hoặc 'practice' = dòng tổng cả phiên
  score int check (score between 0 and 100),
  duration_seconds int check (duration_seconds >= 0),
  created_at timestamptz not null default now()
);
create index if not exists bb_practice_log_child_idx on public.bb_practice_log (child_id, skill, created_at);

alter table public.bb_practice_log enable row level security;
drop policy if exists bb_practice_log_select on public.bb_practice_log;
create policy bb_practice_log_select on public.bb_practice_log for select to authenticated
  using (public.is_admin() or exists (select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid()));
drop policy if exists bb_practice_log_insert on public.bb_practice_log;
create policy bb_practice_log_insert on public.bb_practice_log for insert to authenticated
  with check (public.is_admin() or (public.has_access() and exists (select 1 from public.child_profiles c where c.id = child_id and c.parent_id = auth.uid())));
drop policy if exists bb_practice_log_admin_delete on public.bb_practice_log;
create policy bb_practice_log_admin_delete on public.bb_practice_log for delete to authenticated
  using (public.is_admin());
